### ISSUE TITLE
angular-favicon installation warning when using Angular 8+

### ISSUE THREAD

**Issue by BorntraegerMarc** [imaka/Ngx-Favicon#9]
I'm using angular 10:
```
"@angular/common": "10.0.4",
"@angular/core": "10.0.4",
```

However when installing this lib **freshly** I get: `npm WARN angular-favicon@1.0.4 requires a peer of @angular/common@^7.2.0 but none is installed. You must install peer dependencies yourself.`

I see this lib is using angular 10 as well in package.json: https://github.com/imaka/Ngx-Favicon/blob/701a2132e4744006a2c04e5a668650a901c85c95/package.json#L15

Where does this peer dependency come from? Is it a mistake?

**Comment by JairoMarques** [comment]
Same here!
Package "angular-favicon" has an incompatible peer dependency to "@angular/common" (requires "^7.2.0" (extended), would install "11.2.0")

**Comment by imaka** [comment]
This is now fixed.
